name: .NET CI

on:
  push:
    branches: [ 'dev', 'main' ]
  pull_request:
    branches: [ 'dev', 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '10.0.x' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore
        run: dotnet restore "loan-approval-dotnet/loan-approval-dotnet.slnx"

      - name: Build
        run: dotnet build "loan-approval-dotnet/loan-approval-dotnet.slnx" --configuration Release --no-restore

      - name: Test
        run: dotnet test "loan-approval-dotnet/loan-approval-dotnet.slnx" --configuration Release --no-build --verbosity normal
